baseURL = "https://www.thatrocketx.com/"
DefaultContentLanguage = "it"
title = "that Rocket X"
theme = "tema"
PaginatePath = "pag"
disqusShortname = "thatrocketx"
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "AMP", "RSS"]
  taxonomy = ["HTML", "AMP", "RSS"]
  section = ["HTML", "AMP", "RSS"]
[outputFormats]
  [outputFormats.RSS]
  noUgly = true
  baseName = "index"
  path = "rss"
  [outputFormats.AMP]
  baseName = "index-amp"
  path= ""
[languages]
  [languages.it]
    languageName = "Italiano"
    LanguageCode = "it-IT"
    weight = 1
    contentDir = "content/italiano"
  [languages.en]
    languageName = "English"
    LanguageCode = "en"
    weight = 2
    title = "that Rocket X (EN)"
    contentDir = "content/english"
 [taxonomies]
      category = "categories"
      tag = "tags"
      country = "countries"
      series = "series"
      city = "cities"
[minify]
  enable = true
  [[minify.htmlOptions]]
    KeepDocumentTags = true
    KeepConditionalComments = true
    KeepEndTags = true
    KeepDefaultAttrVals = true
  [[minify.cssOptions]]
    Decimals = -1
    KeepCSS2 = true
[related]
threshold = 80.0
includeNewer = true
toLower = true
  [[related.indices]]
  name = "series"
  weight = 100.0
  [[related.indices]]
  name = "cities"
  weight = 90.0
  [[related.indices]]
  name = "categories"
  weight = 90.0
  [[related.indices]]
  name = "countries"
  weight = 80.0
  [[related.indices]]
  name = "keywords"
  weight = 70.0
[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe= true
  [markup.goldmark.extensions]
      footnote = true
      typographer = true
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2
